apiVersion: v1
kind: Pod
metadata:
  name: cm-p1
spec:
  containers:
    - name: cm-p1-c1
      image: nginx
      env:
        - name: k1
          valueFrom:
            configMapKeyRef:
              name: cm1
              key: k1
