apiVersion: v1
kind: Pod
metadata:
  name: cm-p3
spec:
  containers:
    - name: cm-p3-c1
      image: busybox
      command: ["sleep", "3600"]
      envFrom:
        - configMapRef:
            name: cm3
