apiVersion: v1
kind: Pod
metadata:
  name: cm-demo-pod-3
spec:
  containers:
    - name: cm-demo-pod-3-container
      image: bash
      envFrom:
        - configMapRef:
            name: cm2
      env:
        - name: GREETING
          value: "Welcome to "
        - name: NAME
          value: "Kubernetes!"
      command: ["echo"]
      args: ["$(GREETING) $(NAME): $(k1) - $(k2) "]
