apiVersion: v1
kind: Pod
metadata:
  name: cm-demo-pod-1
spec:
  containers:
    - image: nginx
      name: cm-demo-pod-1-container
      volumeMounts:
        - name: cm-demo-pod-1-vol
          mountPath: /etc/config
  volumes:
    - name: cm-demo-pod-1-vol
      configMap:
        name: cm2
