apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-pod-2
spec:
  containers:
    - name: mybusybox
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]   # command: [ "/bin/echo", "k1: $(k1), k2: $(k2)" ]
      env:
        - name: SECRET1
          valueFrom:
            secretKeyRef:
              name: s1
              key: password1
        - name: SECRET3
          valueFrom:
            secretKeyRef:
              name: s3
              key: password3