apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-pod
spec:
  containers:
    - name: secret-container-2
      image: alpine
      command: ["sh", "-c"]
      args:
        [
          "echo username: $(cat /etc/secret/username), password: $(cat /etc/secret/password) ",
        ]
      volumeMounts:
        - name: secret-volume         # Mounts the Secret as a volume at /etc/secret.
          mountPath: /etc/secret
          readOnly: true              # It prevents the container from modifying secret data.
  volumes:
    - name: secret-volume       # Creates a file for each key in the secret and Creates a volume of from those files;
      secret:
        secretName: s1
