# Use stringData field, if you want to store plain text directly in secret;
# K8s takes stringData and encodes it using base64 and creates data field internally;
apiVersion: v1
kind: Secret
metadata:
  name: s2
type: Opaque
stringData:
  username: mcheedhe
  password: Welcome123