apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-pre-rollback
  annotations:
    "helm.sh/hook": pre-rollback
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: pre-rollback
          image: busybox
          command: ["sh", "-c", "echo '>>> PRE-ROLLBACK hook executed at:' $(date)"]
