apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-test
  annotations:
    "helm.sh/hook": test
spec:
  restartPolicy: Never
  containers:
    - name: test
      image: busybox
      command: ["sh", "-c", "echo '>>> TEST hook executed at:' $(date) && echo 'Service endpoint:' && wget -qO- {{ .Release.Name }}-svc:{{ .Values.service.port }} | head -5 && echo '>>> TEST PASSED'"]
