# Mount secret data as environment variables in a container
apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  containers:
  - name: secret-container
    image: busybox
    command: ["sh", "-c", "echo S1_USERNAME: $S1_USERNAME, S1_PASSWORD: $S1_PASSWORD, S2_USERNAME: $S2_USERNAME, S2_PASSWORD: $S2_PASSWORD && sleep 3600"]
    env:
    - name: S1_USERNAME     # Defines environment variable, whose value comes from another source
      valueFrom:
        secretKeyRef:
          name: s1          # Secret name
          key: username     # Key in the secret data map;
    - name: S1_PASSWORD
      valueFrom:
        secretKeyRef:
          name: s1
          key: password
    - name: S2_USERNAME
      valueFrom:
        secretKeyRef:
          name: s2
          key: username
    - name: S2_PASSWORD
      valueFrom:
        secretKeyRef:
          name: s2
          key: password