# It is your responsibility to base-64 encode text before storing in data;
# Otherwise, you will get this error: "invalid base-64 data" 
# echo -n 'mcheedhe' | base64		  -> bWNoZWVkaGU=
# echo -n 'Welcome123' | base64 	-> bXktZGItcGFzc3dvcmQ=
apiVersion: v1
kind: Secret
metadata:
  name: s1
type: Opaque
data:
  username: bWNoZWVkaGU=	        # base64 for mcheedhe
  password: bXktZGItcGFzc3dvcmQ= 	# base64 for Welcome123