apiVersion: v1
entries:
  firstchart:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-05-28T08:46:44.11085+05:30"
    description: A Helm chart for Kubernetes
    digest: c6c41f2dfdf3ef8de47a305bb8afcc7ba385ca80697965139e1781c05ec91232
    name: firstchart
    type: application
    urls:
    - firstchart-0.1.0.tgz
    version: 0.1.0
generated: "2022-05-28T08:46:44.109883+05:30"
