apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs1
spec:
  replicas: 3                       # Desired number of replicas/pods;
  selector:
    matchLabels:                    # Monitor Pods with this label!
      app: nginxwebserver
  template:
    metadata:
      labels:                       # Assign this lable to every pod!
        app: nginxwebserver
    spec:
      containers:
        - name: mynginx
          image: nginx