spring.application.name=user-manager

spring.datasource.url= jdbc:mysql://10.248.210.199:3306/mcdemo
spring.datasource.username=denaliwww
spring.datasource.password=denaliwww

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true

server.port=8082