apiVersion: batch/v1
kind: CronJob
metadata:
  name: cj1
spec:
  schedule: '*/1 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: cj1-c1
              image: busybox
              command: ["echo", "Hello from CronJob"]

